config/routes.rb
Rails.application.routes.draw do
  # welcome page
  root 'home#show'

  get '/home', to: "home#show"

  # Authentication, user and session management
  resources :sessions, only: [:create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/today', to: 'day_agendas#today', as: 'today_agenda'
  get '/day_agendas/:id/morning', to: 'day_agendas#morning', as: 'edit_morning_agenda'
  get '/day_agendas/:id/evening', to: 'day_agendas#evening', as: 'edit_evening_agenda'

  # Action
  resources :month_actions, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :day_actions
  resources :day_agendas

  # Plan
  resources :domains do
    resource :plan, only: [:show, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :new, :edit, :create, :update, :destroy]
  end
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :user

  has_one :plan
  has_many :deadlines
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]
  before_action :check_connected

  # GET /domains
  # GET /domains.json
  def index
    @domains = @current_user.domains.order(note: :asc)
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    if @domain.user != @current_user
      redirect_to domains_path
    end
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
    if @domain.user != @current_user
      redirect_to domains_path
    end
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)
    @domain.user = @current_user
    @domain.plan = Plan.new(
        vision: "",
        target: "",
        role: "",
        axis: "",
        resources: ""
    )

    if @domain.save
      redirect_to domains_path
    else
      render :new
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    if @domain.user != @current_user
      redirect_to domains_path
    end

    if @domain.update(update_params)
      redirect_to @domain
    else
      render :edit
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    if @domain.user != @current_user
      redirect_to domains_path
    end

    @domain.destroy
    redirect_to domains_url
  end

  private
  def check_connected
    if @current_user == nil
      render :status => :forbidden, :text => "Page accessible seulement connecté"
    end
  end

  def set_domain
    @domain = Domain.find(params[:id])
  end

  def domain_params
    params.fetch(:domain, {}).permit(:name, :description)
  end

  def update_params
    params.fetch(:domain, {}).permit(:name, :description, :note, :explanation)
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">

    <h1>Modifier domaine</h1>
    <p>
      <%= link_to 'Retour', :back %> |
      <%= link_to 'Voir', @domain %> |
      <%= link_to 'Liste des domaines', domains_path %>
    </p>
  </div>

  <div class="content">
    <%= simple_form_for @domain, class: 'form-horizontal' do |f| %>
        <div class="form-group">
          <%= f.input :name,
                      label: "Nom" %>
        </div>
        <div class="form-group">
          <%= f.input :note,
                      collection: 1..10,
                      label: "Note"
            %>
        </div>

        <div class="form-group">
          <%= f.input :description,
                      as: :text,
                      label: "Description"
          %>
        </div>

        <div class="form-group">
          <%= f.input :explanation,
                      label: "Explication de la note",
                      as: :wysihtml5,
                      wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'image':false, 'blockquote': false } }
          %>
        </div>

        <%= f.submit 'Mettre à jour', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Domaines</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th>Note</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= link_to domain.name, domain_plan_path(domain) %> </td>
        <td><%= domain.description %></td>
        <td><%= domain.note %></td>
        <td>
          <%= link_to raw('<span class="glyphicon glyphicon-file" />'), domain %>
          <%= link_to raw('<span class="glyphicon glyphicon-edit" />'), edit_domain_path(domain) %>
          <%= link_to raw('<span class="glyphicon glyphicon-remove" />'), domain, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter un domaine', new_domain_path %>

app/views/domains/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">

    <h1>Nouveau domaine</h1>
    <p>
      <%= link_to 'Retour', domains_path %>
    </p>
  </div>

  <div class="content">
    <%= form_for @domain, class: 'form-horizontal' do |f| %>
        <div class="form-group">
          <%= f.label 'Nom', class: 'control-label' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label 'Description', class: 'control-label' %>
          <%= f.text_field :description, class:'form-control' %>
        </div>

        <%= f.submit 'Créer', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>

app/views/domains/show.html.erb
<p>
  <%= link_to 'Retour', :back %> |
  <%= link_to 'Modifier', edit_domain_path(@domain) %> |
  <%= link_to 'Liste', domains_path %>
</p>

<h1><%= @domain.name %> <%= @domain.note %><br />
  <small><%= @domain.description %></small></h1>
<p>
  <%= raw(@domain.explanation) %>
</p>

<%= link_to 'Plan', domain_plan_path(@domain) %>
<%= link_to 'deadlines', domain_deadlines_path(@domain) %>