config/routes.rb
Rails.application.routes.draw do
  # welcome page
  root 'home#show'

  get '/home', to: "home#show"

  # Authentication, user and session management
  resources :sessions, only: [:create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/today', to: 'day_agendas#today', as: 'today_agenda'
  get '/day_agendas/:id/morning', to: 'day_agendas#morning', as: 'edit_morning_agenda'
  get '/day_agendas/:id/evening', to: 'day_agendas#evening', as: 'edit_evening_agenda'

  # Action
  resources :month_actions, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :day_actions
  resources :day_agendas

  # Plan
  resources :domains do
    resource :plan, only: [:show, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :new, :edit, :create, :update, :destroy]
  end
end

app/models/day_agenda.rb
class DayAgenda < ActiveRecord::Base
  belongs_to :user
end

app/controllers/day_agendas_controller.rb
class DayAgendasController < ApplicationController
  before_action :set_day_agenda, only: [:show, :edit, :morning, :evening, :update, :destroy]

  # GET /day_agendas
  # GET /day_agendas.json
  def index
    @day_agendas = @current_user.day_agendas.all
  end

  def today
    if params[:day]
      day = Date.parse(params[:day])
    else
      day = Date.today
    end

    today = @current_user.day_agendas.find_or_create_by(day: day)

    redirect_to day_agenda_path(today)
  end

  # GET /day_agendas/1
  # GET /day_agendas/1.json
  def show
  end

  # GET /day_agendas/new
  def new
    @day_agenda = @current_user.day_agendas.new
  end

  def edit
  end

  def morning
  end

  def evening
  end

  # POST /day_agendas
  # POST /day_agendas.json
  def create
    @day_agenda = @current_user.day_agendas.new(day_agenda_params)

    respond_to do |format|
      if @day_agenda.save
        format.html { redirect_to @day_agenda, notice: 'Day agenda was successfully created.' }
        format.json { render :show, status: :created, location: @day_agenda }
      else
        format.html { render :new }
        format.json { render json: @day_agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_agendas/1
  # PATCH/PUT /day_agendas/1.json
  def update
    respond_to do |format|
      if @day_agenda.update(day_agenda_params)
        format.html { redirect_to @day_agenda, notice: 'Day agenda was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_agenda }
      else
        format.html { render :edit }
        format.json { render json: @day_agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_agendas/1
  # DELETE /day_agendas/1.json
  def destroy
    @day_agenda.destroy
    respond_to do |format|
      format.html { redirect_to day_agendas_url, notice: 'Day agenda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_agenda
      @day_agenda = @current_user.day_agendas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_agenda_params
      params.require(:day_agenda).permit(:date, :agenda, :quote, :targets, :actions, :success)
    end
end

app/helpers/day_agendas_helper.rb
module DayAgendasHelper
end

app/views/day_agendas/_form.html.erb
<%= simple_form_for(@day_agenda) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :agenda %>
    <%= f.input :quote %>
    <%= f.input :targets %>
    <%= f.input :actions %>
    <%= f.input :success %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/day_agendas/edit.html.erb
<h1>Editing Day Agenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @day_agenda %> |
<%= link_to 'Back', day_agendas_path %>

app/views/day_agendas/evening.html.erb
<h1>Revue de la journée</h1>

<blockquote><%= @day_agenda.quote %></blockquote>

<%= simple_form_for(@day_agenda) do |f| %>
    <div class="form-inputs">
      <%= f.input :success,
                  label: "Mes succès",
                  rows: 3,
                  as: :wysihtml5,
                  wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'image':false, 'blockquote': false } },
                  placeholder: "Aujourd'hui, j'ai eu du succès :" %>
    </div>

    <div class="form-actions">
      <%= f.submit 'Clôturer la journée', class: 'btn btn-default'  %>
    </div>
<% end %>

app/views/day_agendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Day Agendas</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Agenda</th>
      <th>Quote</th>
      <th>Targets</th>
      <th>Actions</th>
      <th>Success</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_agendas.each do |day_agenda| %>
      <tr>
        <td><%= day_agenda.date %></td>
        <td><%= day_agenda.agenda %></td>
        <td><%= day_agenda.quote %></td>
        <td><%= day_agenda.targets %></td>
        <td><%= day_agenda.actions %></td>
        <td><%= day_agenda.success %></td>
        <td><%= day_agenda.user %></td>
        <td><%= link_to 'Show', day_agenda %></td>
        <td><%= link_to 'Edit', edit_day_agenda_path(day_agenda) %></td>
        <td><%= link_to 'Destroy', day_agenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day agenda', new_day_agenda_path %>

app/views/day_agendas/morning.html.erb
<h1>Ma journée…</h1>

<%= simple_form_for(@day_agenda) do |f| %>
    <div class="form-inputs">
      <%= f.input :quote,
                  label: "Citation inspirante",
                  placeholder: "Lorsque vous faites un choix dans la vie, n'oubliez pas de vivre. -- Samuel Johnson"
      %>

      <%= f.input :targets,
                  label: "Mes buts",
                  rows: 3,
                  as: :wysihtml5,
                  wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'image':false, 'blockquote': false } },
                  placeholder: "Rappel des buts ultimes que je cherche à atteindre" %>

      <%= f.input :actions,
                  label: "Grandes actions",
                  as: :wysihtml5,
                  wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'image': false, 'color': true, 'blockquote': false } },
                  placeholder: "Quelles sont les grandes actions que je vais accomplir aujourd'hui ?" %>

      <%= f.input :agenda, as: :wysihtml5,
                  label: "Agenda de la journée",
                  wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'image':false, 'color': true, 'blockquote': false } },
                  placeholder: "De quoi est-ce que ma journée sera faite ?"
      %>

    </div>

    <div class="form-actions">
      <%= f.submit 'Débuter la journée', class: 'btn btn-default'  %>
    </div>
<% end %>

app/views/day_agendas/show.html.erb
<div>
  <%= link_to 'Jour précédent', today_agenda_path(day: @day_agenda.day - 1) %> |
  <%= link_to 'Aujourd\'hui', today_agenda_path %> |
  <%= link_to 'Jour Suivant', today_agenda_path(day: @day_agenda.day + 1) %>
</div>

<h1><%= l(@day_agenda.day, format: :full) %></h1>

<div>
  <%= link_to 'Débuter la journée', edit_morning_agenda_path(@day_agenda) %> |
  <%= link_to 'Finir la journée', edit_evening_agenda_path(@day_agenda) %>
</div>

<div>
  <p>
  <blockquote>
    <%= @day_agenda.quote %>
  </blockquote>
  </p>
</div>

<div class="col-md-6">

  <%= raw(@day_agenda.agenda) %>
</div>

<div class="col-md-6">
  <p>
    <strong>Buts ultimes de la journée</strong><br />

    <%= raw(@day_agenda.targets) %>
  </p>

  <p>
    <strong>Grandes actions de la journée</strong><br />

    <%= raw(@day_agenda.actions) %>
  </p>

  <p>
    <strong>Succès accomplis</strong> <br />

    <%= raw(@day_agenda.success) %>
  </p>
</div>