config/routes.rb
Rails.application.routes.draw do
  # welcome page
  root 'home#show'

  get '/home', to: "home#show"

  # Authentication, user and session management
  resources :sessions, only: [:create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/today', to: 'day_agendas#today', as: 'today_agenda'
  get '/day_agendas/:id/morning', to: 'day_agendas#morning', as: 'edit_morning_agenda'
  get '/day_agendas/:id/evening', to: 'day_agendas#evening', as: 'edit_evening_agenda'

  # Action
  resources :month_actions, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :day_actions
  resources :day_agendas

  # Plan
  resources :domains do
    resource :plan, only: [:show, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :new, :edit, :create, :update, :destroy]
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]
  before_action :check_connected

  def show
    @plan = @domain.plan
    if @plan == nil
      logger.fatal "No plan for domain #{@domain.id}"
      @domain.plan = Plan.create(
          vision: "",
          target: "",
          role: "",
          axis: "",
          resources: ""
      )
      @plan = @domain.plan
    end
  end

  def edit
  end

  def update
    if @domain.plan.update(plan_params)
      redirect_to domain_plan_path(@domain)
    else
      format.html { render :edit }
    end
  end

  def destroy
    @plan = @domain.plan
    plan.vision = ""
    plan.target = ""
    plan.role = ""
    plan.axis = ""
    plan.resources = ""
    plan.save!
    redirect_to [@domain, @plan]
  end

  private
  def set_domain
    @domain = Domain.find(params[:domain_id])
  end

  def plan_params
    params.fetch(:plan, {}).permit(:vision, :target, :role, :axis, :resources, :domain, :plan)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">

    <h1>Plan <em><%= @domain.name %></em></h1>
    <p><%= @domain.description %></p>
    <p>
      <%= link_to 'Voir', domain_plan_path(@domain) %> |
      <%= link_to 'Liste des domaines', domains_path %>
    </p>
  </div>

  <div class="content">
    <%= simple_form_for @domain.plan, url: domain_plan_path(@domain),class: 'form-horizontal' do |f| %>
        <%= f.input :vision, placeholder: "Quelle est ma vision ultime ? Qu'est-ce qui me fait rêver ?",
                    label: "Vision : quoi ?", as: :wysihtml5,
                    wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'blockquote': false } },
                    class: 'form-control' %>
        <%= f.input :target,
                    placeholder: "Quels sont mes buts ultimes ? Pourquoi est-ce que je veux atteindre cette vision ?",
                    label: "But : pourquoi ?", as: :wysihtml5,
                    wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'blockquote': false } },
                    class:'form-control' %>
        <%= f.input :role, placeholder: "Qu'est-ce que je vais faire ?",
                    label: "Rôle : qui ?", as: :wysihtml5,
                    wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'blockquote': false } },
                    class:'form-control' %>
        <%= f.input :axis, placeholder: "Quels sont les axes sur lesquels je vais me focaliser ?",
                    label: "Axes : domaines à développer ?", as: :wysihtml5,
                    wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'blockquote': false } },
                    class:'form-control' %>
        <%= f.input :resources,
                    placeholder: "Quelles sont les ressources que je vais devoir utiliser ? (Cours, contacts, …)",
                    label: "Ressources : comment ?", as: :wysihtml5,
                    wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'blockquote': false } },
                    class: 'form-control' %>
        <%= f.input :plan,
                    placeholder: "Actions à mettre en œuvre pour atteindre les objectifs (sur l'année, chaque mois/semaine/jour).",
                    label: "Plan d'action", as: :wysihtml5,
                    wysihtml5: { locale: "fr-FR", toolbar: {'font-styles': false, 'color': true, 'blockquote': false } },
                    class: 'form-control' %>
        <%= f.submit 'Mettre à jour', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>

app/views/plans/show.html.erb
<p>
  <%= link_to 'Modifier', edit_domain_plan_path(@plan) %> |
  <%= link_to 'Deadlines', domain_deadlines_path(@domain) %> |
  <%= link_to 'Liste des domaines', domains_path %>
</p>

<h1>Plan <%= link_to @domain.name, @domain %> <%= link_to raw('<span class="glyphicon glyphicon-edit" />'), edit_domain_plan_path(@plan) %></h1>

<h2>Vision ultime</h2>

<%=raw @plan.vision %>

<h2>But ultime</h2>

<%=raw @plan.target %>

<h2>Rôles</h2>

<%=raw @plan.role %>

<h2>Axes à développer</h2>

<%=raw @plan.axis %>

<h2>Ressources</h2>

<%=raw @plan.resources %>

<h2>Plan d'action</h2>

<%=raw @plan.plan %>