config/routes.rb
Rails.application.routes.draw do
  # welcome page
  root 'home#show'

  get '/home', to: "home#show"

  # Authentication, user and session management
  resources :sessions, only: [:create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/today', to: 'day_agendas#today', as: 'today_agenda'
  get '/day_agendas/:id/morning', to: 'day_agendas#morning', as: 'edit_morning_agenda'
  get '/day_agendas/:id/evening', to: 'day_agendas#evening', as: 'edit_evening_agenda'

  # Action
  resources :month_actions, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :day_actions
  resources :day_agendas

  # Plan
  resources :domains do
    resource :plan, only: [:show, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :new, :edit, :create, :update, :destroy]
  end
end

app/models/day_action.rb
class DayAction < ActiveRecord::Base
  belongs_to :user
  attr_accessor :hours, :minutes

end

app/models/day_agenda.rb
class DayAgenda < ActiveRecord::Base
  belongs_to :user
end

app/models/deadline.rb
class Deadline < ActiveRecord::Base
  belongs_to :domain
  belongs_to :month_action
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :user

  has_one :plan
  has_many :deadlines
end

app/models/month_action.rb
class MonthAction < ActiveRecord::Base
  belongs_to :user
  has_one :deadline
end

app/models/plan.rb
class Plan < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :domains
  has_many :month_actions
  has_many :day_actions
  has_many :day_agendas

  def self.from_omniauth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
    user
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]
  before_action :check_connected

  # GET /domains
  # GET /domains.json
  def index
    @domains = @current_user.domains.order(note: :asc)
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    if @domain.user != @current_user
      redirect_to domains_path
    end
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
    if @domain.user != @current_user
      redirect_to domains_path
    end
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)
    @domain.user = @current_user
    @domain.plan = Plan.new(
        vision: "",
        target: "",
        role: "",
        axis: "",
        resources: ""
    )

    if @domain.save
      redirect_to domains_path
    else
      render :new
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    if @domain.user != @current_user
      redirect_to domains_path
    end

    if @domain.update(update_params)
      redirect_to @domain
    else
      render :edit
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    if @domain.user != @current_user
      redirect_to domains_path
    end

    @domain.destroy
    redirect_to domains_url
  end

  private
  def check_connected
    if @current_user == nil
      render :status => :forbidden, :text => "Page accessible seulement connecté"
    end
  end

  def set_domain
    @domain = Domain.find(params[:id])
  end

  def domain_params
    params.fetch(:domain, {}).permit(:name, :description)
  end

  def update_params
    params.fetch(:domain, {}).permit(:name, :description, :note, :explanation)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if @current_user
      redirect_to today_agenda_path
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]
  before_action :check_connected

  def show
    @plan = @domain.plan
    if @plan == nil
      logger.fatal "No plan for domain #{@domain.id}"
      @domain.plan = Plan.create(
          vision: "",
          target: "",
          role: "",
          axis: "",
          resources: ""
      )
      @plan = @domain.plan
    end
  end

  def edit
  end

  def update
    if @domain.plan.update(plan_params)
      redirect_to domain_plan_path(@domain)
    else
      format.html { render :edit }
    end
  end

  def destroy
    @plan = @domain.plan
    plan.vision = ""
    plan.target = ""
    plan.role = ""
    plan.axis = ""
    plan.resources = ""
    plan.save!
    redirect_to [@domain, @plan]
  end

  private
  def set_domain
    @domain = Domain.find(params[:domain_id])
  end

  def plan_params
    params.fetch(:plan, {}).permit(:vision, :target, :role, :axis, :resources, :domain, :plan)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
    rescue
      flash[:warning] = "Problème lors de l'authentification"
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'Au revoir'
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/day_actions_helper.rb
module DayActionsHelper
  def day(number)
    ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"][number]
  end
end

app/helpers/day_agendas_helper.rb
module DayAgendasHelper
end

app/helpers/deadlines_helper.rb
module DeadlinesHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/month_actions_helper.rb
module MonthActionsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_menu.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"
       aria-haspopup="true" aria-expanded="true">
      Actions<span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Journée", today_agenda_path %></li>
      <li><%= link_to "Semaine", day_actions_path %></li>
      <li><%= link_to "Année", month_actions_path %></li>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"
       aria-haspopup="true" aria-expanded="true">
      Planifier<span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Domaines", domains_path %></li>
      <li role="separator" class="divider"></li>
      <% @current_user.domains.order(note: :asc).each do |domain| %>
          <li><%= link_to "Plan "+domain.name, domain_plan_path(domain) %></li>
      <% end %>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"
       aria-haspopup="true" aria-expanded="true">
      Échéances<span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <% @current_user.domains.order(note: :asc).each do |domain| %>
          <li><%= link_to domain.name, domain_deadlines_path(domain) %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Persdev</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="col-md-10">
    <% if current_user %>
        <%= render "layouts/menu" %>
    <% end %>
  </div>
  <div class="col-md-2">
    <% if current_user %>
        <strong><%= current_user.name %></strong> <br />
        <%= link_to "Se déconnecter", signout_path, id: "sign_out" %>
    <% else %>
        <%= link_to image_tag('fb_connect.png', border: 0), "/auth/facebook", id: "sign_in" %>
    <% end %>
  </div>

  <div class="col-md-12">
    <%= yield %>
  </div>
</div>

</body>
</html>